spring:
    data:
        mongodb:
            uri: mongodb://pp_user:pp_password@${app.mongo.host}:${app.mongo.port}/pointing-poker
    mail:
        host: 192.168.1.202
        port: 465
        username: propertyview-test
        password: Aimoo6Ea
        protocol: smtps
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
        address: propertyview-test@gpsolutions.com

server:
    port: 8989

app:
    mongo:
        host: localhost
        port: 27117
    jwt:
        secret: Gerf5gR5cv6dG
    url: http://localhost:${server.port}/

periodicity:
    every-day-at-3-am: 0 0 3 * * *
    every-minute: 0 * * ? * *